services:
  - type: worker
    name: telegram-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: 8830725169:AAFDAVbK_nUkOb4pzBe1OLYV4hvrOGsI6gw
